version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0
      nodejs: 16
    commands:
      # Make setup script executable and run it
      - chmod +x ./setup-environment.sh
      - ./setup-environment.sh
      
      # Install project dependencies
      - echo "Installing project dependencies..."
      - composer install --no-interaction --no-progress || echo "Composer install failed, continuing build"
      
  pre_build:
    commands:
      # Run any checks before build
      - echo Running pre-build checks...
      - php -v
      # Optional: Run linting or code style checks
      # - vendor/bin/phpcs --standard=PSR12 app/
      # Optional: Run security checks
      # - vendor/bin/security-checker security:check composer.lock
      
  build:
    commands:
      # Run tests
      - echo Running tests...
      - vendor/bin/phpunit --log-junit test-reports/junit.xml
      # Build assets (if using webpack, vite, etc.)
      - echo Building assets...
      - npm install
      - npm run build
      
  post_build:
    commands:
      # Generate any deployment artifacts
      - echo Build completed on `date`
      # Optional: Create environment configuration files
      - cp .env.example .env
      - php artisan config:cache # If Laravel

artifacts:
  files:
    - appspec.yml # AWS CodeDeploy configuration
    - .env
    - app/**/*
    - bootstrap/**/*
    - config/**/*
    - database/**/*
    - public/**/*
    - resources/**/*
    - routes/**/*
    - storage/**/*
    - vendor/**/*
    - composer.json
    - composer.lock
    - artisan
    # Add any other files needed for deployment
  discard-paths: no
  base-directory: '.'

cache:
  paths:
    - vendor/**/*
    - node_modules/**/*

reports:
  phpunit-reports:
    files:
      - test-reports/junit.xml
    file-format: JUNITXML