version: 0.2
phases:
  install: 
    runtime-versions:
      php: 8.0
    commands:
      #install dependencies
      - echo Installing composer...
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      #run any checks before build.
      - echo Running pre-build checks...
      - php -v
      - echo installing PHP dependencies...
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      # options checks like security check and ports check
      # -vendor /bin/security-checker security:check composer.lock

  build:
    commands:
      # run tests
      - echo Running tests..
      - vendor/bin/phpunit --log-junit test-reports/junit.xml
      #build assests (if using web packs, vite, etc.)
      - echo building assets...
      

  post_build:
    commands:
      # genrate any deployment artifacts
      - echo Build complete on `date`
      # Optional: create environment configuration file
      - cp .env.example .env
      - php artisan config:cache #if laravel

artifacts:
  files:
    - appspec.yml #AWS CodeDeploy Configuration
    - .env
    - app/**/*
    - bootstrap/**/*
    - config/**/*
    - database/**/*
    - public/**/*
    - vendor/**/*
    - composer.json
    - composer.lock
    - artisan

    #add any other files needed for deployment
  discard-paths: no
  base-directory: '.'

cache:
  path:
    - vendor/**/*
    - node_modules/**/*

reports:
  phpunit-reports:
    files:
      - test-report/junit.xml
    file-format: JUNITXML